// =====================================================================
// The wallet facade: shielded + unshielded + dust, from one seed
// =====================================================================
// Why this exists alongside src/wallet.ts:
//
// `@midnight-ntwrk/wallet@5.0.0` builds a SHIELDED-only wallet and derives
// its address with the generic `test` network prefix. Preview and preprod
// want `mn_addr_preview1…` / `mn_addr_preprod1…`, and fees on the current
// stack are paid in DUST, which is generated by registering NIGHT. None of
// that is reachable through the shielded-only wallet.
//
// So funding and fee payment go through `@midnightntwrk/wallet-sdk`
// instead -- note the org has no hyphen, and is a different org from the
// `@midnight-ntwrk` packages used for the contract itself. Both are real.
//
// Shape follows the official wallet developer guide.
// =====================================================================

import * as ledger from '@midnight-ntwrk/ledger-v8';
import { Buffer } from 'node:buffer';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { AccountKey, HDWallet, Roles, type Role } from '@midnightntwrk/wallet-sdk-hd';
import { WalletFacade, type DefaultConfiguration } from '@midnightntwrk/wallet-sdk-facade';
import { ShieldedWallet } from '@midnightntwrk/wallet-sdk-shielded';
import { DustWallet } from '@midnightntwrk/wallet-sdk-dust-wallet';
import {
  UnshieldedWallet,
  createKeystore,
  PublicKey,
} from '@midnightntwrk/wallet-sdk-unshielded-wallet';
// The developer guide imports InMemoryTransactionHistoryStorage from the
// unshielded-wallet package; in the published 1.2.0 tree it lives in
// wallet-sdk-abstractions and its constructor requires an Effect schema.
// A deployment driver keeps no transaction history, so the no-op storage
// is both correct and one fewer thing to get wrong.
import { NoOpTransactionHistoryStorage } from '@midnightntwrk/wallet-sdk-abstractions';

import { PROOF_SERVER, type NetworkConfig } from './network.js';
import { ONCHAIN_ROOT } from './wallet.js';

/**
 * Derive one role key, stepping the address index if the curve rejects a
 * candidate. The guide does this recursively; a bounded loop makes the
 * termination condition explicit.
 */
function deriveRoleKey(accountKey: AccountKey, role: Role, index = 0): Buffer {
  for (let i = index; i < index + 32; i++) {
    const r = accountKey.selectRole(role).deriveKeyAt(i);
    if (r.type === 'keyDerived') return Buffer.from(r.key);
  }
  throw new Error(`no valid key for role ${role} within 32 indices`);
}

export type DerivedKeys = ReturnType<typeof deriveAllKeys>;

export function deriveAllKeys(seedHex: string) {
  const seed = Uint8Array.from(Buffer.from(seedHex, 'hex'));
  const hd = HDWallet.fromSeed(seed);
  if (hd.type !== 'seedOk') throw new Error(`seed rejected: ${JSON.stringify(hd)}`);

  const account = hd.hdWallet.selectAccount(0);
  const shieldedSeed = deriveRoleKey(account, Roles.Zswap);
  const dustSeed = deriveRoleKey(account, Roles.Dust);
  const unshieldedKey = deriveRoleKey(account, Roles.NightExternal);

  // The SDK asks for root key material to be cleared once leaves are out.
  hd.hdWallet.clear();

  return {
    shielded: {
      seed: shieldedSeed,
      keys: ledger.ZswapSecretKeys.fromSeed(shieldedSeed),
    },
    dust: {
      seed: dustSeed,
      key: ledger.DustSecretKey.fromSeed(dustSeed),
    },
    unshielded: unshieldedKey,
  };
}

/**
 * How the sync stream is batched. Off by default.
 *
 * The SDK batches with `size: 10, timeout: 1ms, spacing: 4ms`
 * (`wallet-sdk-dust-wallet/dist/v1/Sync.js`), which looks like an obvious
 * thing to raise when a first sync has to apply a million events.
 *
 * It was raised, to `size: 500, timeout: 50ms, spacing: 0`, and MEASURED:
 * the dust stream ran at roughly 1,100 events per minute with the larger
 * batches and roughly 1,500 with the SDK's own -- no better, possibly
 * worse. The bottleneck is upstream of the batching, in how fast the
 * indexer's dust subscription delivers. So the default here is the SDK's
 * behaviour, and the knob is left exposed rather than removed, because a
 * different indexer may well behave differently.
 *
 *   MIDNIGHT_SYNC_BATCH=500   use larger batches
 *   unset, or 0               leave the SDK's defaults alone
 */
function batchConfig() {
  const size = Number(process.env.MIDNIGHT_SYNC_BATCH ?? 0);
  if (!Number.isFinite(size) || size <= 0) return undefined;
  return { size, timeout: 50, spacing: 0 };
}

/**
 * A floor under the fee, so a transaction always spends some DUST.
 *
 * On a quiet network the computed fee can round to zero. A zero fee means
 * the wallet selects no DUST inputs, which leaves an empty `DustActions`
 * set, and the ledger refuses that transaction as malformed:
 *
 *   1010: Invalid Transaction: Custom error: 117   (NotNormalized)
 *   "Transaction is not in normal form — most often an idle-devnet zero
 *    fee that produced an empty DUST spend set"
 *
 * from Midnight's own node-error catalogue. The recommended remedy there
 * is exactly this parameter. Observed here on preview: the dust
 * registration reported a fee of `1`, and `issueCredential` — a larger
 * transaction, but on the same near-zero fee schedule — was rejected with
 * 117 until this was set.
 *
 * It is an overhead, not a fixed price: the wallet adds it to whatever the
 * real fee is, so it costs a negligible amount of DUST and never
 * underpays.
 */
const FEE_OVERHEAD = BigInt(process.env.MIDNIGHT_FEE_OVERHEAD ?? 1_000_000);

export function configFor(cfg: NetworkConfig): DefaultConfiguration {
  return {
    networkId: cfg.networkId,
    costParameters: { feeBlocksMargin: 5, additionalFeeOverhead: FEE_OVERHEAD },
    batchUpdates: batchConfig(),
    relayURL: new URL(cfg.node.replace(/^http/, 'ws')),
    provingServerUrl: new URL(PROOF_SERVER),
    indexerClientConnection: {
      indexerHttpUrl: cfg.indexer,
      indexerWsUrl: cfg.indexerWs,
    },
    txHistoryStorage: new NoOpTransactionHistoryStorage(),
  } as DefaultConfiguration;
}

export type OpenFacade = {
  wallet: Awaited<ReturnType<typeof WalletFacade.init>>;
  keys: DerivedKeys;
  keystore: ReturnType<typeof createKeystore>;
  address: string;
};

// ---------------------------------------------------------------------
// Cached wallet state
// ---------------------------------------------------------------------
// A first sync scans the whole chain and takes tens of minutes. Every one
// of the three wallets can serialize its state and be restored from it,
// so a cache turns every subsequent start into seconds.
//
// The cache holds only what the wallet has already derived from PUBLIC
// chain data. It is still gitignored, because it identifies which coins
// belong to this wallet -- that is a privacy leak, not a key leak.
//
// A stale cache is not a correctness problem: the wallet resumes from
// where the cached state left off and syncs the remainder.

type WalletCache = { shielded: string; unshielded: string; dust: string };

function cachePath(network: string): string {
  return join(ONCHAIN_ROOT, `.wallet-cache.${network}.json`);
}

function readCache(network: string): WalletCache | undefined {
  const p = cachePath(network);
  if (!existsSync(p)) return undefined;
  try {
    const c = JSON.parse(readFileSync(p, 'utf8')) as WalletCache;
    return c.shielded && c.unshielded && c.dust ? c : undefined;
  } catch {
    // A corrupt cache is worth exactly one line of warning and then
    // ignoring: a full sync is slow but always correct.
    console.warn(`ignoring unreadable wallet cache at ${p}`);
    return undefined;
  }
}

/** Serialize all three wallets. Call after a sync, not during one. */
export async function saveWalletCache(
  cfg: NetworkConfig,
  open: OpenFacade,
): Promise<void> {
  const w = open.wallet as any;
  const cache: WalletCache = {
    shielded: await w.shielded.serializeState(),
    unshielded: await w.unshielded.serializeState(),
    dust: await w.dust.serializeState(),
  };
  writeFileSync(cachePath(cfg.name), JSON.stringify(cache), { mode: 0o600 });
}

/** Build every wallet from the seed and start them. */
export async function openFacade(
  cfg: NetworkConfig,
  seedHex: string,
  opts: { quiet?: boolean; fresh?: boolean } = {},
): Promise<OpenFacade> {
  const log = opts.quiet ? () => {} : (m: string) => console.log(m);
  const configuration = configFor(cfg);
  const keys = deriveAllKeys(seedHex);
  const keystore = createKeystore(keys.unshielded, cfg.networkId as never);

  const cache = opts.fresh ? undefined : readCache(cfg.name);

  log(`network      ${cfg.name}`);
  log(`address      ${String(keystore.getBech32Address())}`);
  log(`proof server ${PROOF_SERVER}`);
  log(cache ? 'starting wallets from cached state…' : 'starting wallets…');

  const wallet = await WalletFacade.init({
    configuration,
    shielded: (config: any) =>
      cache
        ? ShieldedWallet(config).restore(cache.shielded)
        : ShieldedWallet(config).startWithSecretKeys(keys.shielded.keys),
    unshielded: (config: any) =>
      cache
        ? UnshieldedWallet(config).restore(cache.unshielded)
        : UnshieldedWallet(config).startWithPublicKey(PublicKey.fromKeyStore(keystore)),
    dust: (config: any) =>
      cache
        ? DustWallet(config).restore(cache.dust)
        : DustWallet(config).startWithSecretKey(
            keys.dust.key,
            ledger.LedgerParameters.initialParameters().dust,
          ),
  } as any);

  await wallet.start(keys.shielded.keys, keys.dust.key);

  return { wallet, keys, keystore, address: String(keystore.getBech32Address()) };
}

/**
 * Wait for a full sync, reporting progress.
 *
 * `waitForSyncedState()` alone is a silent wait, and a fresh wallet on a
 * public network scans the entire chain -- hundreds of thousands of blocks
 * on preview, millions on preprod. A silent wait of that length is
 * indistinguishable from a hang, so this subscribes to the state stream
 * and prints the applied/highest indices the wallets already publish.
 *
 * It resolves on the same condition `waitForSyncedState()` uses; the
 * subscription only observes.
 */
export async function waitSynced(
  open: OpenFacade,
  opts: { quiet?: boolean; everyMs?: number } = {},
): Promise<void> {
  const { wallet } = open;
  if (opts.quiet) {
    await wallet.waitForSyncedState();
    return;
  }

  const everyMs = opts.everyMs ?? 15_000;
  const started = Date.now();
  let last = 0;

  const sub = wallet.state().subscribe((s: any) => {
    const now = Date.now();
    if (now - last < everyMs) return;
    last = now;

    // The completion test is `highestRelevantWalletIndex - appliedIndex
    // <= 0 && isConnected` (wallet-sdk-abstractions/dist/SyncProgress.js).
    // `highestIndex` is a different, larger number and is NOT what the
    // wait is waiting for -- printing it produces a progress line that
    // never reaches its own target, which is worse than printing nothing.
    const fmt = (p: any) => {
      if (!p) return 'n/a';
      const applied = p.appliedIndex ?? 0n;
      const target = p.highestRelevantWalletIndex ?? 0n;
      const gap = target - applied;
      return `${applied}/${target}${gap > 0n ? ` (−${gap})` : ' ✓'}${p.isConnected ? '' : ' [offline]'}`;
    };

    const mins = ((now - started) / 60_000).toFixed(1);
    console.log(
      `  [${mins}m] shielded ${fmt(s.shielded?.progress)}` +
        `  unshielded ${fmt(s.unshielded?.progress)}` +
        `  dust ${fmt(s.dust?.progress)}`,
    );
  });

  try {
    await wallet.waitForSyncedState();
  } finally {
    sub.unsubscribe();
  }
}
