// =====================================================================
// Register NIGHT for DUST generation
// =====================================================================
//   npx tsx src/register-dust.ts preview
//
// NIGHT cannot pay transaction fees. DUST can, and DUST is generated by
// registering NIGHT UTXOs. Until that registration lands there is no way
// to pay for a contract deployment, so this runs first.
//
// The registration is itself a transaction, and it has to cover its own
// fee -- hence the wait for enough projected DUST before submitting.
// =====================================================================

import { resolveNetwork } from './network.js';
import { loadOrCreateSeed } from './wallet.js';
import { openFacade, saveWalletCache, waitSynced } from './facade.js';

const cfg = resolveNetwork(process.argv[2]);
const seed = loadOrCreateSeed(cfg.name);

const open = await openFacade(cfg, seed);
const { wallet, keystore } = open;

/**
 * Balances and UTXO values are bigints, which JSON.stringify throws on.
 * Formatting them explicitly is not cosmetic: a throw here happens AFTER
 * a full chain sync, so it costs half an hour to rediscover.
 */
const showBalances = (b: Record<string, bigint> | undefined): string =>
  b === undefined
    ? '{}'
    : Object.entries(b)
        .map(([token, v]) => `${token.slice(0, 10)}…=${v}`)
        .join('  ') || '(none)';

try {
  console.log('syncing — a fresh wallet scans the whole chain');
  await waitSynced(open);
  const state: any = await wallet.waitForSyncedState();
  console.log('synced');

  // Written before anything else can throw: a full scan costs tens of
  // minutes, and losing it to a later error is the failure mode this
  // whole cache exists to prevent.
  await saveWalletCache(cfg, open);
  console.log('wallet state cached — the next start will not rescan');

  const unshielded = state.unshielded;
  const dust = state.dust;

  // UtxoWithMeta: { utxo, meta: { ctime, registeredForDustGeneration } }.
  // The registration flag lives on `meta`, not on the utxo -- reading it
  // off the wrong level silently classifies every utxo as unregistered.
  const night: any[] = [...(unshielded?.availableCoins ?? [])];
  const dustBalance: bigint = dust?.balance ? dust.balance(new Date()) : 0n;

  console.log(`\nNIGHT utxos    ${night.length}`);
  console.log(`unshielded     ${showBalances(unshielded?.balances)}`);
  console.log(`DUST balance   ${dustBalance}`);

  if (night.length === 0) {
    console.error('\nNo NIGHT to register. Fund the address from the faucet first.');
    process.exit(1);
  }

  const unregistered = night.filter((u) => u.meta?.registeredForDustGeneration !== true);
  console.log(`unregistered   ${unregistered.length}`);

  if (unregistered.length === 0) {
    console.log('\nEvery NIGHT utxo is already registered. Nothing to do.');
    process.exit(0);
  }

  // Ask what the registration will cost, then wait until the projected DUST
  // covers it. Submitting before that fails the transaction's own fee guard.
  const est: any = await (wallet as any).estimateRegistration(unregistered);
  console.log(`\nregistration fee   ${est?.fee}`);

  if (est?.fee) {
    console.log('waiting for enough generated dust to cover it…');
    await (wallet as any).waitForGeneratedDust(unregistered, est.fee, {
      timeoutMs: 30 * 60_000,
    });
    console.log('covered');
  }

  console.log('\nsubmitting registration');
  // NOT signed again here. `registerNightUtxosForDustGeneration` delegates
  // to `createDustActionTransaction`, whose step 5 already runs the recipe
  // through `signRecipe` -- stamping both the unshielded offers and the
  // dust registration. Signing a second time would stamp a transaction
  // that is already signed.
  const recipe = await (wallet as any).registerNightUtxosForDustGeneration(
    unregistered,
    keystore.getPublicKey(),
    (payload: Uint8Array) => keystore.signData(payload),
  );
  const tx = await (wallet as any).finalizeRecipe(recipe);
  const txId = await (wallet as any).submitTransaction(tx);

  console.log(`\nregistered. tx ${txId}`);
  console.log('DUST now accrues against the registered NIGHT.');
} catch (e) {
  console.error('\nregistration failed');
  console.error(e);
  process.exit(1);
} finally {
  await (wallet as any).stop?.();
}
